export interface UserProfile {
    first_name?: string,
    last_name?: string,
    email?: string,
    date_joined?: Date,
    date_of_birth?: Date,
    gender?: string,
    location?: string,
    profile_pic?: any,
    userName?: string,
    userLocation?: string,
    userImage?: string,
    numberOfFriends?: number,
    posts?: Array<number>,
    bio?: string,
    interest?: Array<string>,
    phone?: string,
    friend_list?: Array<number>,
}
// "id": 1,
//     "password": "pbkdf2_sha256$600000$8e8vCu615WZ36N9BS7fXop$tSrf/7x4YHeB4IzcJrEohvnTTSJAbU70tZ2F1fuSkDs=",
//     "last_login": "2024-02-01T13:22:36.594572Z",
//     "is_superuser": true,
//     "username": "raza",
//     "first_name": "Shoaib",
//     "last_name": "Ansari",
//     "email": "raza@cybage.com",
//     "is_staff": true,
//     "is_active": true,
//     "date_joined": "2024-02-01T11:52:08Z",
//     "date_of_birth": "2024-02-07",
//     "gender": "Male",
//     "location": "Ind",
//     "phone": "2",
//     "profile_pic": null,
//     "groups": [],
//     "user_permissions": [],
//     "interest": [],
//     "friend_list": [],
//     "send_list": [],
//     "pending_list": []