# Generated by Django 4.2.9 on 2024-01-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialuser',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
